apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrs
  annotations:
    kubernetes.io/change-cause: "updated image to v3"
spec:
  replicas: 4 

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      env: dev

  template:
    metadata:
      labels:
        env: dev
    spec:
       containers:
        - name: my-cont
          image: shaikmustafa/paytm:movie
          ports:
            - containerPort: 80