apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
spec:
  ingressClassName: nginx
  rules:

    - host: jenkins.buildwithbharat.online 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myjenkins
                port:
                  number: 8080


    - host: movie.buildwithbharat.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: movie-service
                port:
                  number: 80