apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
  annotatisons:
    kubernetes.io/change-cause: "v-1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      env: testing
  template:
    metadata:
      name: mydeply
      labels:
        env: testing
    spec:
      containers:
        - name: my-cont
          image: nginx
          ports:
            - containerPort: 80