apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
  annotations:
    kubernetes.io/change-cause: "v-1.0"
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: env
        operator: In
        values:
          - testing
          - prod

      - key: tier
        operator: In
        values:
          - "3"

  template:
    metadata:
      name: my-deployment
      labels:
        env: testing
        tier: "3"
  
    spec:
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80