apiVersion: v1
kind: Pod
metadata:
  name: my-cm-pod

spec:
    containers:
      - name: my-cont
        image: nginx
        ports:
          - containerPort: 80

        env:
          - name: APP_MODE
      
  